# используем язык Java.
language: java
jdk:
  - openjdk8
# используем режим обычного пользователя для сборки проекта.
sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN="mnliaIFG_qPPWV_cCobueQ"
  keep_history: true
  on:
    branch: master


# Отправлять уведомление на почту teenager_08@inbox.ru если сборка упала
notifications:
  email:
    recipients:
      -teenager_08@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always